### ISSUE TITLE
Set up DNS for beyond-translation.scaife-viewer.org

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/translation-alignments-stack#1]
@jtauber when you're able, please set up a CNAME record as follows:

```
beyond-translation.scaife-viewer.org CNAME beyond-translation.scaife.eldarion.com
```

(I'm using `.eldarion.com` DNS because I'm not entirely sure where I want traffic to be served from, so if you can set up to the Eldarion CNAME, I can move it without having to keep bugging you 😄)

**Comment by jtauber** [comment]
Done
